name: Calculate Estimated Hours

on: [push, pull_request]

jobs:
  count_loc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Count Lines of Code
        id: cloc
        run: |
          cloc_output=$(cloc --json .)
          total_lines=$(echo "$cloc_output" | jq '.SUM.code')
          echo "total_lines=$total_lines" >> $GITHUB_ENV

      - name: Calculate Estimated Hours
        id: calculate_hours
        run: |
          lines=${{ env.total_lines }}
          estimated_minutes=$((lines * 2))
          estimated_hours=$(echo "scale=2; $estimated_minutes / 60" | bc)
          echo "Estimated Hours: $estimated_hours"
          echo "estimated_hours=$estimated_hours" >> $GITHUB_OUTPUT

      - name: Output Working Hours
        run: |
          echo "| Metric          | Value   |"
          echo "|-----------------|---------|"
          echo "| Number of Lines | ${{ env.total_lines }}     |"
          echo "| Working Hours | ${{ steps.calculate_hours.outputs.estimated_hours }} Hrs |"
